package analysis

import (
	"testing"

	"github.com/BushidoCyb3r/Archer/internal/config"
	"github.com/BushidoCyb3r/Archer/internal/model"
)

func newDNSTestAnalyzer() *Analyzer {
	a := New(config.Default(), "", nil, nil)
	a.feodoIPs = map[string]bool{}
	a.urlhausIPs = map[string]bool{}
	a.urlhausHosts = map[string]bool{}
	return a
}

func findingOfType(fs []model.Finding, typ string) *model.Finding {
	for i := range fs {
		if fs[i].Type == typ {
			return &fs[i]
		}
	}
	return nil
}

// TestDNSBeaconing_ClosesCadenceGap is the §2g exit-goal invariant: a
// regular-cadence, low-entropy, low-diversity DNS heartbeat to a fixed
// FQDN — the Cobalt-Strike DNS C2 shape — must now produce a DNS
// Beaconing finding, and must still slip the two detectors it slipped
// before (DNS Tunneling: entropy/diversity too low; conn Beaconing:
// IP-pair keyed, no conn.log). Asserting the gap-closure plus the
// continued-miss on the other two is the end-to-end invariant; a
// regression in the scorer, the keying, or the composition fails here
// even if the broad golden is regenerated by mistake.
func TestDNSBeaconing_ClosesCadenceGap(t *testing.T) {
	a := newDNSTestAnalyzer()
	findings := a.Analyze([]string{"testdata/zeek/dns_beacon/dns.log"})

	b := findingOfType(findings, "DNS Beaconing")
	if b == nil {
		t.Fatalf("DNS Beaconing did not fire on the cadence fixture; got types: %v", findingTypes(findings))
	}
	if b.Severity != model.SevCritical {
		t.Errorf("DNS Beaconing severity = %s; want CRITICAL", b.Severity)
	}
	if b.SrcIP != "192.168.2.60" || b.DstIP != "update-svc.net" || b.DstPort != "53" {
		t.Errorf("DNS Beaconing target = %s → %s:%s; want 192.168.2.60 → update-svc.net:53",
			b.SrcIP, b.DstIP, b.DstPort)
	}
	if b.Score < 80 {
		t.Errorf("DNS Beaconing score = %d; want >= 80 for a perfectly regular heartbeat", b.Score)
	}
	// Sprint-1 structured fields must be populated on this beacon type
	// too (they feed §2e sub-score filtering and persist via 0018).
	if b.SampleSize != 60 {
		t.Errorf("SampleSize = %d; want 60", b.SampleSize)
	}
	if b.MeanInterval < 299 || b.MeanInterval > 301 {
		t.Errorf("MeanInterval = %v; want ~300", b.MeanInterval)
	}
	if b.TSScore <= 0 {
		t.Errorf("TSScore = %v; want > 0 (timing axis populated)", b.TSScore)
	}
	if b.DSScore != 0 {
		t.Errorf("DSScore = %v; want 0 (DNS has no data-size axis — must not overload the column)", b.DSScore)
	}

	// Exit goal: the two detectors this shape slipped before still
	// produce nothing for it.
	if hasFindingType(findings, "DNS Tunneling") {
		t.Error("DNS Tunneling fired on the low-entropy/low-diversity fixture — it should still slip it")
	}
	if hasFindingType(findings, "Beaconing") {
		t.Error("conn-level Beaconing fired without a conn.log — impossible unless keying changed")
	}
}

// TestDNSBeaconing_DefersHighDiversityToDGA codifies the diversity-gate
// invariant: a high-subdomain-diversity apex is exfil-shaped and owned
// by DNS Subdomain DGA, so DNS Beaconing must not also fire on it even
// when the cadence is perfectly regular (the dns_subdomain_diversity
// fixture is exactly that — 50 unique subdomains, 1s spacing). Without
// the gate, pure timing regularity would double-emit a HIGH finding on
// the same evidence.
func TestDNSBeaconing_DefersHighDiversityToDGA(t *testing.T) {
	a := newDNSTestAnalyzer()
	findings := a.Analyze([]string{"testdata/zeek/dns_subdomain_diversity/dns.log"})

	if !hasFindingType(findings, "DNS Subdomain DGA") {
		t.Fatalf("setup: DNS Subdomain DGA should fire on the diversity fixture; got: %v", findingTypes(findings))
	}
	if hasFindingType(findings, "DNS Beaconing") {
		t.Error("DNS Beaconing fired on a high-diversity apex — the diversity gate is not holding")
	}
}

// TestDNSBeaconing_IgnoresNXDOMAINFlood codifies the NXDOMAIN-exclusion
// invariant: an NXDOMAIN-dominated stream is the DNS NXDOMAIN Flood
// detector's responsibility (a sinkholed/dead C2, with resolver-retry
// timing contamination). DNS Beaconing must not also fire on it and
// double-count the evidence.
func TestDNSBeaconing_IgnoresNXDOMAINFlood(t *testing.T) {
	a := newDNSTestAnalyzer()
	findings := a.Analyze([]string{"testdata/zeek/dns_nxdomain_flood/dns.log"})

	if !hasFindingType(findings, "DNS NXDOMAIN Flood") {
		t.Fatalf("setup: DNS NXDOMAIN Flood should fire on the flood fixture; got: %v", findingTypes(findings))
	}
	if hasFindingType(findings, "DNS Beaconing") {
		t.Error("DNS Beaconing fired on an NXDOMAIN flood — NXDOMAIN records must be excluded from cadence")
	}
}
